export const iconList = [
  "loading",
  "check-circle",
  "close-circle",
  "info-circle",
  "left-circle",
  "down-circle",
  "minus-circle",
  "plus-circle",
  "play-circle",
  "right-circle",
  "time-circle",
  "time out",
  "up-circle",
  "warning-circle",
  "sync",
  "undo",
  "redo",
  "reload",
  "reload time",
  "message",
  "poweroff",
  "logout",
  "pie chart",
  "setting",
  "eye",
  "location",
  "edit-square",
  "export",
  "Import",
  "close-square",
  "down-square",
  "layout",
  "left-square",
  "play-square",
  "control",
  "detail",
  "minus-square",
  "plus-square",
  "right-square",
  "up-square",
  "calculator",
  "check-square",
  "add user",
  "delete team",
  "delete user",
  "addteam",
  "user",
  "team",
  "area chart",
  "line chart",
  "bar chart",
  "point map",
  "mobile",
  "file search",
  "file-add",
  "file-exclamation",
  "file-unknown",
  "file",
  "file-text",
  "delete",
  "bell",
  "rest",
  "skin",
  "home",
  "filter",
  "funnel plot",
  "like",
  "unlike",
  "unlock",
  "lock",
  "folder",
  "folder-open",
  "folder-add",
  "calendar",
  "barcode",
  "camera",
  "cloud-upload",
  "cloud",
  "cloud-download",
  "notification",
  "sound",
  "qrcode",
  "image",
  "mail",
  "table",
  "id card",
  "credit card",
  "heart",
  "error",
  "star",
  "wifi",
  "edit",
  "api",
  "link",
  "pushpin",
  "phone",
  "wrench",
  "right",
  "left",
  "up",
  "down",
  "arrowright",
  "arrowup",
  "arrowleft",
  "arrowdown",
  "check",
  "close",
  "line",
  "minus",
  "question",
  "check-circle-fill",
  "left-circle-fill",
  "down-circle-fill",
  "minus-circle-fill",
  "close-circle-fill",
  "info-circle-fill",
  "up-circle-fill",
  "right-circle-fill",
  "plus-circle-fill",
  "question-circle-fill",
  "compass-fill",
  "play-circle-fill",
  "warning-circle-fill",
  "time-circle-fill",
  "heart-fill",
  "pie chart-circle-fil",
  "message-fill",
  "check-square-fill",
  "down-square-fill",
  "minus-square-fill",
  "close-square-fill",
  "left-square-fill",
  "play-square-fill",
  "up-square-fill",
  "right-square-fill",
  "plus-square-fill",
  "carry out-fill",
  "calendar-fill",
  "calculator-fill",
  "app store-fill",
  "file-exclamation-fil",
  "file-add-fill",
  "file-fill",
  "file-unknown-fill",
  "folder-add-fill",
  "folder-fill",
  "folder-open-fill",
  "image-fill",
  "id card-fill",
  "credit card-fill",
  "delete-fill",
  "notification-fill",
  "rest-fill",
  "shopping-fill",
  "skin-fill",
  "sound-fill",
  "bell-fill",
  "filter-fill",
  "gift-fill",
  "home-fill",
  "location-fill",
  "cloud-fill",
  "eye-fill",
  "like-fill",
  "unlike-fill",
  "star-fill",
  "unlock-fill",
  "api-fill",
  "phone-fill",
  "edit-fill",
  "pushpin-fill",
  "rocket-fill",
  "camera-fill",
  "error-fill",
  "mail-fill",
  "setting-fill",
  "alipay",
  "taobao",
  "aliwangwang",
  "apple",
  "android",
  "android-fill",
  "apple-fill",
  "QQ",
  "weibo",
  "wechat-fill",
  "alipay-circle-fill",
  "aliwangwang-fill",
  "github-fill",
  "QQ-circle-fill",
  "taobao-circle-fill",
  "weibo-circle-fill",
  "alipay-square-fill",
  "zoom out",
  "zoom in",
  "comment",
  "signal-fill",
  "switch user",
  "caret-down",
  "backward",
  "caret-up",
  "caret-right",
  "caret-left",
  "fast-backward",
  "forward",
  "fast-forward",
  "search",
  "step-backward",
  "step-forward",
  "plus",
  "eye close-fill",
  "eye-close",
  "clear",
  "compress"
];
